// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDYZVLt_hV7YwEVuoRCBbvKfiRIELEYcYo',
    appId: '1:133690224329:web:def2becccb80926d37a718',
    messagingSenderId: '133690224329',
    projectId: 'chilaqueen-d4d94',
    authDomain: 'chilaqueen-d4d94.firebaseapp.com',
    storageBucket: 'chilaqueen-d4d94.firebasestorage.app',
    measurementId: 'G-HSY1FGMG54',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCzY-HhRz_PBcL1eBGa1ETJM611hjOlHuw',
    appId: '1:133690224329:android:553056edbad63ace37a718',
    messagingSenderId: '133690224329',
    projectId: 'chilaqueen-d4d94',
    storageBucket: 'chilaqueen-d4d94.firebasestorage.app',
  );
}
