name: Flutter CI

on:
  push:
  pull_request:

jobs:
  flutter_ci:
    name: Analyze & Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout del repositorio
        uses: actions/checkout@v4

      - name: Instalar Flutter (stable)
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          cache: true

      - name: flutter pub get
        run: flutter pub get

      - name: flutter analyze
        run: flutter analyze --no-fatal-infos

      - name: flutter test
        run: flutter test --reporter=expanded
